#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=VISUAL-PROMPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=12:00:00
#SBATCH --output=visual_prompt.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

root=/scratch-local/$USER
mkdir -p $root

# Run 1: Zero-shot CLIP on CIFAR-10 with standard text prompt
code_dir=./
pip install git+https://github.com/openai/CLIP.git
python $code_dir/main.py --method fixed_patch --visualize_prompt --dataset cifar10 --epochs 100
python $code_dir/main.py --method fixed_patch --visualize_prompt --dataset cifar100 --epochs 100
python $code_dir/main.py --method padding --visualize_prompt --dataset cifar100 --epochs 100
python $code_dir/main.py --method padding --visualize_prompt --dataset cifar100 --epochs 100
