#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=CLIPZS-CIFAR10
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=CLIPZS.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

root=/scratch/$USER
mkdir -p $root

# Run 1: Zero-shot CLIP on CIFAR-10 with standard text prompt
code_dir=./
pip install git+https://github.com/openai/CLIP.git
python $code_dir/clipzs.py --dataset cifar10 --split test --root $root
